version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Install dependencies"
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping Deployment package"
      - cd lib
      - zip -r9 ../lf-search.zip .
      - zip -r9 ../lf-index.zip .
      - cd ..
      - cd Lambdas
      - mv search-photos.py ../lambda_function.py
      - cd ..
      - zip -r lf-search.zip lambda_function.py
      - mv lambda_function.py Lambdas/search-photos.py
      - cd Lambdas
      - mv index-photos.py ../lambda_function.py
      - cd ..
      - zip -r lf-index.zip lambda_function.py
      - mv lambda_function.py Lambdas/index-photos.py

  post_build:
    commands:
      - echo "Updating Lambda Functions"
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://lf-search.zip
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://lf-index.zip
      - echo "Completed"