version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file sam_template.yml --s3-bucket artifact-bucket-test-a2 --output-template-file outSamTemplate.yaml
artifacts:
  type: zip
  files:
    - sam_template.yml
    - outSamTemplate.yaml